services:
  postgres:
    image: postgres:17
    container_name: mypostgres
    restart: always                                                                   
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: sifre123
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
                                            